import React, { useState } from 'react';
import { Box, Typography, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Grid } from '@mui/material';
import Barcode from 'react-barcode-generator';
import { QRCodeCanvas } from 'qrcode.react';

const InvoicePdf = () => {

    const [eWayBillNumber, seteWayBillNumber] = useState('281814197003');

    return (
        <Box sx={{ padding: 3, fontFamily: 'Arial, sans-serif' }} component={Paper}>
            {/* Header Section */}
            <Box sx={{ marginLeft: 3, marginBottom: 2, marginTop: 5 }}>
                <Typography variant="h2" gutterBottom>e-Way Bill</Typography>

                {/* QR Code Section */}
                <Box sx={{ display: 'flex', marginBottom: 0, marginLeft: '85%', marginTop: '-70px' }}>
                    <QRCodeCanvas value={eWayBillNumber} size={110} />
                </Box>
            </Box>

            {/* E-WAY BILL Details Section */}
            <Box sx={{ marginBottom: 2 }}>
                <Typography
                    variant="h4"
                    component={Paper}
                    sx={{
                        padding: 1.5,
                        border: '1px solid #ddd',
                        backgroundColor: '#eef2f6',
                    }}
                > 1. E-WAY BILL DETAILS </Typography>
                <TableContainer sx={{ marginTop: 2, boxShadow: 2, backgroundColor: '#e3f2fd' }}>
                    <Table>
                        <TableBody>
                            <TableRow>
                                <TableCell sx={{ fontWeight: 'bold' }}>eWay Bill No:</TableCell>
                                <TableCell>{eWayBillNumber}</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Generated Date:</TableCell>
                                <TableCell>22/08/2024 06:28 PM</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Generated By:</TableCell>
                                <TableCell>27AAY FR546 3Q1ZX</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell sx={{ fontWeight: 'bold' }}>Mode:</TableCell>
                                <TableCell>Road</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Approx Distance:</TableCell>
                                <TableCell>1296km</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Valid Upto:</TableCell>
                                <TableCell>29/08/2024</TableCell>
                            </TableRow>
                            <TableRow>
                                <TableCell sx={{ fontWeight: 'bold' }}>Type:</TableCell>
                                <TableCell>Outward - Supply</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Document Details:</TableCell>
                                <TableCell>Tax Invoice - 98 - 22/08/2024</TableCell>
                                <TableCell sx={{ fontWeight: 'bold' }}>Transaction Type:</TableCell>
                                <TableCell>Bill To - Ship To</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </TableContainer>
            </Box>

            {/* Address Details Section */}
            <Box sx={{ marginBottom: 2 }}>
                <Typography
                    variant="h4"
                    component={Paper}
                    sx={{
                        padding: 1.5,
                        border: '1px solid #ddd',
                        backgroundColor: '#eef2f6'
                    }}
                > 2. ADDRESS DETAILS </Typography>
                <Grid container spacing={2} sx={{ marginTop: -1 }}>
                    {/* From Section */}
                    <Grid item xs={12} sm={6}>
                        <Typography
                            sx={{
                                fontWeight: 'bold',
                                fontSize: '1.1rem',
                                marginBottom: 1,
                                marginLeft: 2,
                                color: '#388e3c',
                            }}
                        > From </Typography>
                        <Paper
                            variant="outlined"
                            sx={{
                                padding: 2,
                                backgroundColor: '#c8e6c3',
                                borderColor: '#388e3c',
                                boxShadow: 2
                            }}
                        >
                            <Typography>
                                <strong>GSTIN:</strong> <span style={{ color: '#2e7d32' }}>27AAY FR546 3Q1ZX</span>
                            </Typography>
                            <Typography>R P Packaging Solution</Typography>
                            <Typography>MAHARASHTRA</Typography>
                            <Typography sx={{ marginTop: 2, color: '#388e3c' }}>
                                <strong>:: Dispatch From ::</strong>
                            </Typography>
                            <Typography>SHED NO 1 SURVEY NO 70 PLOT NO</Typography>
                            <Typography>SATPUR NASHIK</Typography>
                            <Typography>Nashik, MAHARASHTRA-422007</Typography>
                        </Paper>
                    </Grid>
                    {/* To Section */}
                    <Grid item xs={12} sm={6}>
                        <Typography
                            sx={{
                                fontWeight: 'bold',
                                fontSize: '1.1rem',
                                marginBottom: 1,
                                color: '#e64a19',
                                marginLeft: 2,
                            }}
                        > To </Typography>
                        <Paper
                            variant="outlined"
                            sx={{
                                padding: 2,
                                backgroundColor: '#ffccbc',
                                borderColor: '#e64a19',
                                boxShadow: 2
                            }}
                        >
                            <Typography>
                                <strong>GSTIN:</strong> <span style={{ color: '#d32f2f' }}>29ABM CS198 2P1ZA</span>
                            </Typography>
                            <Typography>SCM AIPACKS PRIVATE LIMITED</Typography>
                            <Typography>KARNATAKA</Typography>
                            <Typography sx={{ marginTop: 2, color: '#e64a19' }}>
                                <strong>:: Ship To ::</strong>
                            </Typography>
                            <Typography>C/o K2 LOGISTICS</Typography>
                            <Typography>No 91, Kila no 1, village kankrola, near IMT manesat sector -7</Typography>
                            <Typography>Gurugram, Haryana, HARYANA-122505</Typography>
                        </Paper>
                    </Grid>
                </Grid>
            </Box>

            {/* Goods Details Section */}
            <Box sx={{ marginBottom: 2 }}>
                <Typography
                    variant="h4"
                    component={Paper}
                    sx={{
                        padding: 1.5,
                        border: '1px solid #ddd',
                        backgroundColor: '#eef2f6'
                    }}
                > 3. GOODS DETAILS </Typography>
                <TableContainer component={Paper} sx={{ marginTop: 1.5, boxShadow: 2 }}>
                    <Table>
                        <TableHead sx={{ backgroundColor: '#1976d2' }}>
                            <TableRow>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>HSN Code</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Product Name & Description</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Quantity</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Taxable Amount (Rs.)</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Tax Rate</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            <TableRow sx={{ backgroundColor: '#e3f2fd' }}>
                                <TableCell>3923</TableCell>
                                <TableCell>Flc (1400*1100*1120) & Foldable large container</TableCell>
                                <TableCell>50.00 Set</TableCell>
                                <TableCell>310,000.00</TableCell>
                                <TableCell>NE+NE+18.000+0.000+0.00</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </TableContainer>
                <TableContainer component={Paper} sx={{ marginTop: 1.5, boxShadow: 2 }}>
                    <Table>
                        <TableHead sx={{ backgroundColor: '#1976d2' }}>
                            <TableRow>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>Total Taxable Amount</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>CGST Amt</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>SGST Amt</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>IGST Amt</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>CESS Amt</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>CESS Non-Advol Amt</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>Other Amt</strong></TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}><strong>Total Invoice Amount</strong></TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            <TableRow sx={{ backgroundColor: '#e3f2fd' }}>
                                <TableCell>310,000.00</TableCell>
                                <TableCell>0.00</TableCell>
                                <TableCell>0.00</TableCell>
                                <TableCell>55,800.00</TableCell>
                                <TableCell>0.00</TableCell>
                                <TableCell>0.00</TableCell>
                                <TableCell>0.00</TableCell>
                                <TableCell>365,800.00</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </TableContainer>
            </Box>

            {/* Transportation Details Section */}
            <Box sx={{ marginBottom: 2 }}>
                <Typography
                    variant="h4"
                    component={Paper}
                    sx={{
                        padding: 1.5,
                        border: '1px solid #ddd',
                        backgroundColor: '#eef2f6'
                    }}
                > 4. TRANSPORTATION DETAILS </Typography>
                <Box sx={{ marginTop: 1.5, boxShadow: 2, backgroundColor: '#e3f2fd', padding: 2 }}>
                    <Typography
                        sx={{
                            fontSize: '1rem',
                            color: '#333',
                        }}
                    >
                        <strong>Transporter ID & Name:</strong> <span style={{ marginLeft: '70px' }}>27GFHPS7026Q1ZH & SAFE TIMES LOGISTICS</span>
                    </Typography>
                    <Typography
                        sx={{
                            marginTop: 1,
                            fontSize: '1rem',
                            color: '#333',
                        }}
                    >
                        <strong>Transporter Doc. No & Date:</strong> <span style={{ marginLeft: '35px' }}> & 22/08/2024</span>
                    </Typography>
                </Box>
            </Box>

            {/* Vehicle Details */}
            <Box sx={{ marginBottom: 3 }}>
                <Typography
                    variant="h4"
                    component={Paper}
                    sx={{
                        padding: 1.5,
                        border: '1px solid #ddd',
                        backgroundColor: '#eef2f6'
                    }}
                > 5. VEHICLE DETAILS </Typography>
                <TableContainer component={Paper} sx={{ marginTop: 1.5, boxShadow: 2 }}>
                    <Table>
                        <TableHead sx={{ backgroundColor: '#1976d2' }}>
                            <TableRow>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Mode</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Vehicle / Trans Doc No & Dt.</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>From</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Entered Date</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Entered By</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>CEWB No</TableCell>
                                <TableCell sx={{ color: 'white', fontWeight: 'bold' }}>Multi Veh.Info</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            <TableRow sx={{ backgroundColor: '#e3f2fd' }}>
                                <TableCell>Road</TableCell>
                                <TableCell>HR55AK6777</TableCell>
                                <TableCell>Nashik</TableCell>
                                <TableCell>22/08/2024 06:28 PM </TableCell>
                                <TableCell>27AAYFR5463Q1ZX</TableCell>
                                <TableCell>-</TableCell>
                                <TableCell>-</TableCell>
                            </TableRow>
                        </TableBody>
                    </Table>
                </TableContainer>
            </Box>

            {/* Barcode Section */}
            <Box sx={{ display: 'flex', justifyContent: 'center' }}>
                <Barcode value={eWayBillNumber} format="CODE128" width={2} height={50} />
            </Box>

            {/* Footer Section */}
            <Box sx={{ marginTop: 2, textAlign: 'center', fontSize: '8px' }}>
                <Typography>Note*: If any discrepancy in information, please try after some time.</Typography>
            </Box>
        </Box>
    );
};

export default InvoicePdf;
